//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rennga_task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crypto
    {
        public int Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<double> Avg_Rate { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Exchange_Rates { get; set; }
    }
}
